short: shortest-path.cpp
	g++ -std=c++0x -lpthread shortest-path.cpp debug.cpp -o shortest-path
run: short
	./shortest-path $(F) $(O) $(S) $(T)
shortD: shortest-path.cpp
	g++ -g -ggdb -std=c++0x -lpthread shortest-path.cpp debug.cpp -o shortest-path
